### ISSUE TITLE
Jil.DeserializationException

### ISSUE THREAD

**Issue by win32nipuh** [Ravadre/RxRedis#2]
I have executed this test:
1. Modified the test app Program.cs

```
            sbj.OnNext(5);
            sbj.OnNext(6);
            Console.ReadKey();
            sbj.OnNext(7);

            sbj.OnNext(8);
            Console.ReadKey();
            sbj.OnNext(9);
            Console.ReadKey();
            sbj.OnCompleted();

            Console.ReadLine();

```
1. Run external Redis client and subscribed to channel s1
2. Run the test app
3. The external client receives messages, ok.
4. In the external Redis client I published to channel s1 message: 1
5. There is exception:

```
private void OnMessage(RedisChannel redisChannel, RedisValue redisValue)
        {
            var msg = JSON.Deserialize<Message<T>>(redisValue);

```

An exception of type 'Jil.DeserializationException' occurred in Jil.dll but was not handled in user code
Additional information: Expected: {, null

Note. When I run 2 test app (modified as I wrote above) they work fine.

**Comment by Ravadre** [comment]
What do you mean by external redis client, especially in point 4? 

Error hints that a message that was not a JSOn object was published to a channel, which should not happen (and therefore I also assume that no other library / client publishes to this channel but RxRedis, so the protocol is preserved).

**Comment by win32nipuh** [comment]
I have used this client application
https://github.com/caoxinyu/RedisClient

You wrote: " no other library / client publishes to this channel but RxRedis"
Why not? IMHO this approach narrows its usability.

**Comment by Ravadre** [comment]
Ok, so that explains why it crashed and this is intended behavior.

What you tried to do contradicts with what I would like to have implemented, let me explain a bit (and yes, I am aware that without readme, more samples etc. it might be misleading, I will be working on that as soon as I can).
The goal of this library is to provide an ability to use concepts known from Reactive Extensions, namely Subjects and IObservable, but with messages passed through a broker (in this case - Redis). 
If no other information but pure data objects would be passed as you tried to do (using other client), it would be impossible to implement any behaviors other than just passing infinite data stream (because you would not be even able to signal completion), not to mention other behaviors - fe. other Subject types. 
You can see an example of what I am talking with currently implemented AsyncSubject, which works differently by design - messages passed to channel should be ignored and only last message should be published once stream has completed.

To achieve that I have to implement my own protocol to pass all this meta information with messages. This approach it is a bit restrictive for basic case (you just want an infinite stream), but it also allows to implement different behaviors.

So the proper way of using this library is to treat channel and state keys that are created based on subject/observable name provided as black boxes. If you need to pass  stream between 2 processes, first one (publisher) should create a Subject (if other behavior is needed, other kind of Subject, for example AsyncSubject) and then receiver can create Observable to receive messages. Note that, just like with ReactiveX, different kinds of subjects will produce different behavior for clients (observables).

**Comment by win32nipuh** [comment]
Ok, I see, thank you for the description.
When I run 2 your test applications they exchanges by messages successfully.
Is it right way to use 2 applications both as a mixed sub-pub?

**Comment by Ravadre** [comment]
You can exchange messages with Observables, however, by design of how Reactive Extensions works it is a one-way communication (you push data and observe it on observables by subscribing to them). 
RxRedis mimics original behavior as well. Idiomatic way to this would be to create 2 pairs of Subject/Observables, 1 to communicate A->B and 2nd one to communicate B->A.
You can however have many observers observing 1 Observable (most likely in this case - a subject).
I prepared an example to illustrate this, you can find it here: 
[Two way communucation](https://github.com/Ravadre/RxRedis/blob/master/examples/TwoWayCommunication/Program.cs)

Basically, how it works:
1. A service and an client communicate through 2 pairs of Subject/Observable. A service listens to events emmited to clients and on some events - send a response back
2. There's a third object - Sink, which observes all communication between those two passively.

For simplicity those 3 actors are running on their own threads, but in real scenario you could have them split over processes or over network.

Other way to look at it is: You can have 1 Subject (or in more general - publisher) for one topic and  you can have as many Observables connected to it receiving events. So for two-way communication you need publisher/subscriber pair for each endpoint. This is not the most convenient request-response architecture, but making one was not the goal in the first place.

You can also check AsyncSubjects example to see how changing a Subject type can change behavior of Observables that are connected to it (compared to first example you checked out already) - and to create this behavior I had to implement a custom "protocol" and disallow pushing raw data from external clients.

**Comment by win32nipuh** [comment]
Thank you for the sample.
